
services:
  api:
    build: .
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - b_network
    

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    networks:
      - b_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  b_network:
    driver: bridge

volumes:
  db_data:
    driver: local
